# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project 1
pod 'Firebase/Core’

  target 'Project 1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
